name: Build build
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: yarn  --frozen-lockfile

      - run: yarn build
