name: Release  build
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - run: yarn  --frozen-lockfile

      - run: yarn build

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
